#<Amanda Chu and G01381239>
#CS262, Lab Section203
#<P1: A two-player game that randomly generates a 5 letter word 
#and the number of sides for the 2 dices.> 


CC = gcc
CFLAGS = -Wall -pedantic-errors
TARGET = p1_achu4_203

$(TARGET): $(TARGET).c
	$(CC) $(TARGET).c -o $(TARGET) $(CFLAGS)
clean:
	rm $(TARGET)
